apiVersion: v1

kind: Pod

metadata:
  namespace: todo-app
  name: firefox-todo
  labels:
    app: frontend

spec:
  containers:
  - name: myapp
    image: linuxserver/firefox
    ports:
      - containerPort: 3000
