apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: stgclass-todopvc
  namespace: dev-todo

spec: 
  accessModes:
    - ReadWriteOnce
# why readwritemany not use here?
  resources:
    requests:
      storage: 5Gi
  storageClassName: stgclass-tudo
  volumeMode: Filesystem