apiVersion: v1

kind: PersistentVolumeClaim

metadata: 
  namespace: todo-app
  name: stgclass-todopvc
  
spec: 
  accessModes:
    - ReadWriteOnce
# why readwritemany not use here?
  resources:
    requests:
      storage: 5Gi
  storageClassName: stgclass-todo
  volumeMode: Filesystem